# Generated by Django 3.0.7 on 2020-07-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodzina', '0002_auto_20200714_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfids', to='rodzina.Family', verbose_name='Rodzina'),
        ),
    ]
