# Generated by Django 3.0.7 on 2020-06-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rodzina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Znacznik czasu')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodzina.Person', verbose_name='Dziecko')),
            ],
            options={
                'verbose_name': 'Znacznik czasu',
                'verbose_name_plural': 'Znaczniki czasu',
            },
        ),
    ]
